<?php

/**
 * @file
 * Bugsnag.com integration.
 */

/**
 * Implements hook_menu().
 */
function bugsnag_menu() {
  $items = array();
  $items['admin/settings/bugsnag'] = array(
    'title' => 'Bugsnag',
    'description' => 'Integrate with Bugsnag.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bugsnag_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback for Bugsnap settings form.
 */
function bugsnag_form() {
  $library = libraries_get_path('bugsnag');
  $description = isset($library) ? t('Track errors with Bugsnag.') : '<span class="warning">' . t('You must install the Bugsnag library') . '</span>';

  $options = _bugsnag_severity_list();

  $form['bugsnag_limit'] = array(
    '#type' => 'select',
    '#title' => t('Minimum severity to report to Bugsnag'),
    '#options' => $options,
    '#default_value' => variable_get('bugsnag_limit', WATCHDOG_ERROR),
    '#description' => $description,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_libraries_info().
 */
function bugsnag_libraries_info() {
  $libraries['bugsnag'] = array(
    'name' => 'Bugsnag',
    'vendor url' => 'https://bugsnag.com/',
    'version' => 'v1.0.6',
    'download url' => 'https://github.com/bugsnag/bugsnag-php/',
    'path' => 'lib',
    'files' => array(
      'php' => array('bugsnag.php'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_watchdog().
 */
function bugsnag_watchdog($log_entry) {

  $bugsnag_limit = variable_get('bugsnag_limit', WATCHDOG_ERROR);

  if (isset($log_entry['severity']) && $log_entry['severity'] > $bugsnag_limit) {
    return;
  }

  $severity_list = _bugsnag_severity_list();

  $severity = $severity_list[$log_entry['severity']];
  $type = $log_entry['type'];
  $message = $log_entry['message'];

  _bugsnag_load_library('bugsnag');
  Bugsnag::notifyError($severity, $type . ': ' . $message);
}

/**
 * Load Bugsnag library.
 */
function _bugsnag_load_library() {
   if (!class_exists('Bugsnag')) {
    if (!($library_path = _bugsnag_get_path())) {
      return FALSE;
    }
    require_once './'. $library_path .'/lib/bugsnag.php';
  }
  return TRUE;
}

/**
 * Get path to Bugsnag library.
 */
function _bugsnag_get_path() {
  $library_path = libraries_get_path('bugsnag');
  if (!file_exists('./'. $library_path .'/lib/bugsnag.php')) {
    return FALSE;
  }
  return $library_path;
}

/**
 * Return watchdog severity options.
 */
function _bugsnag_severity_list() {
  return array(
    WATCHDOG_EMERGENCY => t('Emergency'),
    WATCHDOG_ALERT => t('Alert'),
    WATCHDOG_CRITICAL => t('Critical'),
    WATCHDOG_ERROR => t('Error'),
    WATCHDOG_WARNING => t('Warning'),
    WATCHDOG_NOTICE => t('Notice'),
    WATCHDOG_INFO => t('Info'),
    WATCHDOG_DEBUG => t('Debug'),
  );
}
